name: Playlist colaborativa
on:
  push:
    branches: [ "main" ]
    paths:
      - 'playlist.src'

permissions:
  contents: write

jobs:
  Crear-Playlist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Escribir
      run: |
        echo "# ðŸŽ¼ðŸŽ¼ La Radio ðŸŽ¼ðŸŽ¼" > Playlist.md
        echo "## de estudiantes de GitHub en CÃ³digoFacilito" >> Playlist.md
        cat playlist.src | awk -F ';' '{printf "%d. %s (%s)\n", NR, $1, $2 }' >> Playlist.md

        echo "" >> Playlist.md
        echo "Â¡Para incluir canciones no edites directamente este fichero!" >> Playlist.md
        echo "Â¡Hazlo incluyendo una lÃ­nea a \`playlist.src\`!" >> Playlist.md
        echo "" >> Playlist.md

    - name: Configurar Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Commit y push
      run: |
        git add Playlist.md
        git commit -m "ðŸŽ¼ðŸŽ¼ La Radio ðŸŽ¼ðŸŽ¼"
        git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
